<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.4.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>b60ea32f-7bbb-4a70-bc3b-3c4c44b9ee6a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CretCollect.App.Server\CretCollect.App.Server.csproj" />
    <ProjectReference Include="..\CretCollect.WebApi\CretCollect.WebApi.csproj" />
  </ItemGroup>

</Project>
