<Project Sdk="Microsoft.NET.Sdk.Web">
    
  <Choose>
    <When Condition="'$(UseLocalCnpSources)' == 'true'">
      <ItemGroup>
        <ProjectReference Include="$(LocalCnpFrameworkRoot)\CretNet.Platform.Blazor.Server\CretNet.Platform.Blazor.Server.csproj" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="CretNet.Platform.Blazor.Server" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <ProjectReference Include="..\CretCollect.ServiceDefaults\CretCollect.ServiceDefaults.csproj" />
    <ProjectReference Include="..\CretCollect.App.Wasm\CretCollect.App.Wasm.csproj" />
      
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

</Project>
